# Generated by Django 4.2.1 on 2023-07-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_text', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_text', models.CharField(max_length=80)),
                ('description_text', models.TextField(max_length=3000)),
                ('illustration_text', models.TextField(max_length=120)),
                ('pub_date', models.DateTimeField(verbose_name='date de publication')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_text', models.CharField(max_length=200)),
                ('description_text', models.CharField(max_length=3000)),
                ('pub_date', models.DateTimeField(verbose_name='date de publication')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.secteur')),
            ],
        ),
        migrations.CreateModel(
            name='Infographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_text', models.CharField(max_length=80)),
                ('description_text', models.TextField(max_length=3000)),
                ('graphique_text', models.TextField(max_length=120)),
                ('source_text', models.TextField(max_length=120)),
                ('periode_enquete_text', models.TextField(max_length=12)),
                ('pub_date', models.DateTimeField(verbose_name='date de publication')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_text', models.CharField(max_length=80)),
                ('description_text', models.TextField(max_length=3000)),
                ('source_text', models.TextField(max_length=120)),
                ('pub_date', models.DateTimeField(verbose_name='date de publication')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Infographie_region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infographie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.infographie')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.region')),
            ],
            options={
                'unique_together': {('infographie', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Article_region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.infographie')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.region')),
            ],
            options={
                'unique_together': {('article', 'region')},
            },
        ),
    ]
