# Generated by Django 4.2.1 on 2023-07-24 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=3000)),
                ('illustration', models.CharField(max_length=120, null=True)),
                ('pub_date', models.DateField(verbose_name='date de publication')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=3000)),
                ('illustration', models.CharField(max_length=120, null=True)),
                ('compteur', models.IntegerField(default=0, null=True)),
                ('pub_date', models.DateField(verbose_name='date de publication')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='content.secteur')),
            ],
        ),
        migrations.CreateModel(
            name='Infographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=3000)),
                ('graphique', models.CharField(max_length=120)),
                ('source', models.CharField(max_length=120)),
                ('periode_enquete', models.TextField(max_length=12)),
                ('compteur', models.IntegerField(default=0, null=True)),
                ('pub_date', models.DateField(verbose_name='date de publication')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.region')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infographies', to='content.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=15000)),
                ('source', models.CharField(max_length=120)),
                ('compteur', models.IntegerField(default=0, null=True)),
                ('pub_date', models.DateField(verbose_name='date de publication')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.region')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Infographie_favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infographie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.infographie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('infographie', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Article_favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('article', 'user')},
            },
        ),
    ]
