# Generated by Django 4.2.1 on 2023-07-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='source_text',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='titre_text',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='infographie',
            old_name='description_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='infographie',
            old_name='graphique_text',
            new_name='graphique',
        ),
        migrations.RenameField(
            model_name='infographie',
            old_name='periode_enquete_text',
            new_name='periode_enquete',
        ),
        migrations.RenameField(
            model_name='infographie',
            old_name='source_text',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='infographie',
            old_name='titre_text',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='nom_text',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='secteur',
            old_name='description_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='secteur',
            old_name='illustration_text',
            new_name='illustration',
        ),
        migrations.RenameField(
            model_name='secteur',
            old_name='nom_text',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='description_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='nom_text',
            new_name='nom',
        ),
    ]
