# Generated by Django 4.2.1 on 2023-07-27 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article_user_infographie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='infographie',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='secteur',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date de publication'),
        ),
    ]
