# Generated by Django 4.2.1 on 2023-07-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_description_text_article_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='infographie',
            name='graphique',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='infographie',
            name='source',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='secteur',
            name='illustration',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='theme',
            name='nom',
            field=models.CharField(max_length=80),
        ),
    ]
