# Generated by Django 4.2.1 on 2023-07-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_article_pub_date_alter_infographie_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infographie',
            name='periode_enquete',
            field=models.CharField(max_length=12),
        ),
    ]
