# Generated by Django 4.2.1 on 2023-07-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_article_source_alter_infographie_graphique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_region',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article'),
        ),
    ]
