# Generated by Django 4.2.1 on 2023-08-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_infographie_periode_enquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secteur',
            name='illustration',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='secteur/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='illustration',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='theme/'),
        ),
    ]
