# Generated by Django 4.2.1 on 2023-07-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_article_region_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secteur',
            name='illustration',
        ),
        migrations.AddField(
            model_name='theme',
            name='illustration',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
