# Generated by Django 4.2.1 on 2023-07-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_secteur_illustration_theme_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='compteur',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='infographie',
            name='compteur',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='compteur',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
