# Generated by Django 4.2.1 on 2023-08-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_secteur_illustration_alter_theme_illustration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
