# Generated by Django 4.2.1 on 2023-07-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_infographie_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='content.theme'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='content.secteur'),
        ),
    ]
