# Generated by Django 4.2.1 on 2023-07-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_article_theme_alter_theme_secteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=15000),
        ),
    ]
