# Generated by Django 4.2.1 on 2023-07-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infographie',
            name='pub_date',
            field=models.DateField(verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='secteur',
            name='pub_date',
            field=models.DateField(verbose_name='date de publication'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='pub_date',
            field=models.DateField(verbose_name='date de publication'),
        ),
    ]
