# Generated by Django 4.2.1 on 2023-07-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_infographie_pub_date_alter_secteur_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secteur',
            name='illustration',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
